' =======================================
' Nodes PlantUML Theme
' Author: Dominik Hadl
' Version: 1.0
' 
' Description: Used for importing in PlantUML diagrams to get consistent Nodes styling.
' Usage: 
'   !includesub NodesTheme.puml!<DIAGRAM_TYPE>
'   fx.
'   !includesub NodesTheme.puml!ACTIVITY
' 
' TODO: Move this to github
' =======================================
@startuml

' == Variables ==

!$fontName = "Arial"
!$fontSize = "12"

' == General ==

skinparam BackgroundColor #FFF
skinparam Shadowing false
skinparam Dpi 100
skinparam RoundCorner 8
skinparam BoxPadding 20

' == Default ==

skinparam default {
    FontName $fontName
    FontSize $fontSize
    MonospacedFontName Source Code Pro
}

' == Title ==

skinparam Title {
    BorderThickness 2
    BorderRoundCorner 20
    BorderColor #B52C6E
    BackgroundColor #D83F73
    FontStyle bold
    FontColor #FFF
    FontSize 16
}

' == Arrow ==

skinparam Arrow {
    Color #D83F73
}

' == Note ==

skinparam Note {
	BackgroundColor #f9ccff
	BorderColor #7C3D83
	FontSize 8
}

' == Activity Diagram ==

skinparam Activity {
    FontName $fontName
    FontSize $fontSize
    BackgroundColor #F8F7F7
    BorderColor #E6D9E7

    DiamondFontName $fontName
    DiamondFontSize $fontSize
    DiamondFontStyle bold
    DiamondBackgroundColor #FFEBF0
    DiamondBorderColor #D83F73

    StartColor #D83F73
    EndColor #D83F73
}

'  == Partition ==

skinparam Partition {
  BackgroundColor #ffccdd
  BorderColor #B52C6E
  FontStyle bold
}

' == Actor ==

skinparam Actor {
    BackgroundColor #FFF
    BorderColor #B52C6E
    FontStyle bold
}

' == Participant ==

skinparam Participant {
    BackgroundColor #F8F7F7
    BorderColor #E6D9E7
    Padding 20
}

' == Entity ==

skinparam Entity {
    BackgroundColor #D83F73
    BorderColor #B52C6E
    FontStyle bold
}

' == Database ==

skinparam Database {
    BackgroundColor #D83F73
    BorderColor #B52C6E
    FontStyle bold
}

' == Sequence Diagram ==

skinparam Sequence {
    MessageAlignment center
    MessageTextAlignment center

    BoxBackgroundColor #F8F7F7
    BoxBorderColor #E6D9E7
    BoxPadding 10

    DividerBackgroundColor #D83F73
    DividerBorderColor #B52C6E
    DividerFontColor #FFF

    GroupBackgroundColor #fff
    GroupBodyBackgroundColor #ffccdd
    GroupBorderColor #B52C6E

    TitleFontName $fontName
    TitleFontSize 16
    TitleFontStyle bold
    TitleFontColor #FFF
}

' ======================

header Made by Nodes with ❤
footer Generated on %date()

@enduml